apiVersion: v1
kind: Pod
metadata:
  name: mybox
spec:
  restartPolicy: Always
  containers:
  - name: mybox
    image: busybox
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi    
    command:
      - sleep
      - "3600"
    env:
      - name: mykey
        valueFrom:
          configMapKeyRef:
            name: cm-example
            # if the cm file does not have this key, the pod will be "CreateContainerConfigError" state.
            key: mykey

