#* probe is to examine whether the pod is working properly.
#* there are three kind of probes. 
# 1. Startup probes: to know when a container has started
# 2. Readiness probes: to know when a container is ready to accept traffic
# !     a failing readiness probe will stop the application from receiving traffic.
# 3. Liveness probes: indicates whether the code is running or not.
# !     a failing liveness probe will restart the container.
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-example
spec:
  containers:
  - name: liveness
    image: busybox
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi    
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 15; rm -rf /tmp/healthy; sleep 3600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 2
